choco install git
choco install wget
choco install curl
choco install python
choco install corretto11jdk
choco install maven
choco install intellijidea-community
choco install slack
choco install vscode
choco install postman