choco install -y git
choco install -y wget
choco install -y curl
choco install -y python
choco install -y corretto11jdk
choco install -y maven
choco install -y intellijidea-community
choco install -y slack
choco install -y vscode
choco install -y postman