choco upgrade -y --limit-output git
choco upgrade -y --limit-output wget
choco upgrade -y --limit-output curl
choco upgrade -y --limit-output python
choco upgrade -y --limit-output corretto11jdk
choco upgrade -y --limit-output maven
choco upgrade -y --limit-output intellijidea-community
choco upgrade -y --limit-output slack
choco upgrade -y --limit-output vscode
choco upgrade -y --limit-output postman