$user = whoami

Write-Host "Is Git installed?"
$env:PATH -match "git"
Write-Host "Is WGET installed?"
$env:PATH -match "wget"
Write-Host "Is CURL installed?"
$env:PATH -match "curl"
Write-Host "Is Python installed?"
$env:PATH -match "python"
Write-Host "Is Java installed?"
$env:PATH -match "java"
Write-Host "Is Maven installed?"
$env:PATH -match "maven"
Write-Host "Is IntelliJ installed?"
Test-Path -Path "C:\Users\$user\AppData\Local\JetBrains\IdeaIC*"
Write-Host "Is Slack installed?"
Test-Path -Path "C:\Users\$user\AppData\Local\slack"
Write-Host "Is VS Code installed?"
Test-Path -Path "C:\Users\$user\AppData\Local\Programs\Microsoft VS Code"
Write-Host "Is Postman installed?"
Test-Path -Path "C:\Users\$user\Appdata\Local\Postman"