name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        working-directory: ./choc-approach
        run: |
          rm "C:\ProgramData\Chocolatey\" -r -force
      - name: Kickoff
        working-directory: ./choc-approach
        run: |
          powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force; .\ignition.ps1
      - name: Verify Installation
        working-directory: ./choc-approach
        run: |
          powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force; .\verify.ps1